### PR TITLE
Add linter workflow

### LINKED ISSUE #29: Add lint workflow
for example

```
name: Lint Python
on: [push]
jobs:
  call-run-python-linters:
    uses: openclimatefix/.github/.github/workflows/python-lint.yml@main
```

Various code changes might need to happen due to this

### PR DESCRIPTION
**Pull request by mduffin95**
# Pull Request

## Description

I saw this issue was listed as a good first issue and thought I'd take a stab at it. This PR adds a linting workflow.

Fixes #29 

## How Has This Been Tested?

All changes were made using `autoflake` and `isort`. There are no functional changes.

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/nowcasting/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by peterdudfield** [comment]
Hi @mduffin95 

Sorry we just had a bit of a tidy up and simply, would you be able to rebase your changes of `main`

**Comment by simlmx** [comment]
Thanks @mduffin95 ! We needed to be able to format/lint the code from within the repo so I have added this in 
#53 . If you rebase the PR only `.github/workflows/linters.yml` should remain (as the other PR has formatted the code).

**Comment by simlmx** [comment]
Actually it will be simpler to run the linting defined in this repo directly. Sorry about the inconvenience and thanks again @mduffin95

**Comment by mduffin95** [comment]
no problem

**Pull request closed without merging**
