### PR TITLE
updated version of sqlalchemy in poetry

### LINKED ISSUE #88: Update SQLAlchemy > 2.0

### PR DESCRIPTION
**Pull request by roshnaeem**
# Pull Request

## Description
Updated version of `sqlalchemy`. 

### Python Versions
It worked for me with the Python 3.11 version. 

I tried first with Python 3.10 which threw me the incompatible error in poetry 
```
The currently activated Python version 3.10.8 is not supported by the project (^3.11).
Trying to find and use a compatible version. 
```

I faced issues with Python 3.12 too. Python 3.11 is compatible with both `poetry` and `sqlalchemy`.  

Fixes #88

### CODE REVIEW

**Comment by peterdudfield** [comment]
Thanks @roshnaeem

**Comment by peterdudfield** [comment]
It looks like the tests failed - https://github.com/openclimatefix/pv-site-datamodel/actions/runs/8318096910/job/22759627236

Can you do a fix, test locally? and then a new PR?

**Comment by roshnaeem** [comment]
@peterdudfield, I tried running the test, but I was getting this error. 


Screenshot 2024-03-17 at 10 29 48 PM

**Comment by peterdudfield** [comment]
you have to install `testcontainers`, if this is not in the Readme.md that would be great to add

**Comment by roshnaeem** [comment]
@peterdudfield, yes it was a problem on my end with the python version. Fixed it and opened a PR which passes all pytests. 
Please check https://github.com/openclimatefix/pv-site-datamodel/pull/108

**Pull request merged**
