### PR TITLE
run alembic migrations instead of using sqlalchemy to migrate test db

### PR DESCRIPTION
**Pull request by mduffin95**
Initial change required for work on #165. 

Currently the tests do not seem to test the actual alembic migrations but instead use sqlalchemy directly to build the DB schema. I guess this is problematic because it's not really testing what's in prod.

Because as part of #165 I'd like to use a DB trigger it makes sense to instead apply the alembic migrations so that it can be tested. The existing test setup wouldn't add the trigger.

### CODE REVIEW

**Comment by mduffin95** [comment]
Not sure why the github actions workflow isn't running

**Comment by peterdudfield** [comment]
> Not sure why the github actions workflow isn't running

The CI is currently set up only to run when a PR is opened. I need (or you could if you fancy it) change this so it runs on every change

**Comment by mduffin95** [comment]
@peterdudfield I've fixed this PR and also added #171 to add the `synchronize` trigger.

**Comment by mduffin95** [comment]
@peterdudfield yep it's ready

**Pull request merged**
