### PR TITLE
Add client table

### PR DESCRIPTION
**Pull request by Bvr4**
# Pull Request

## Description

This PR refers to the issue #148 Client table.

Added client table with client_name. Mapped the table with sites.
Made alembic migration.
Added read functions : get_sites_by_blient_name and get_client_by_name (with the option of creating the client if it doesn't exist.
Added write functions : create_client, edit_client, assign_site_to_client.

Fixes #

## How Has This Been Tested?

I created the tests associated with each function, via pytest. 
For that, I made small modifications to conftest.py, like the creation of a client fixture.

- [x] Yes

_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_

- [ ] Yes

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by peterdudfield** [comment]
Hi @Bvr4 

Thanks so much for this. 

You ok to adjust the alembic migration, its just becasue another one has sneaked in this before this. You can either update the hash in the migrations, or just re make it. 

I think other than, that, its ready to go

**Comment by Bvr4** [comment]
OK, I'll take a look at it next week.

**Comment by peterdudfield** [comment]
> OK, I'll take a look at it next week.

Thanks @Bvr4

**Comment by Bvr4** [comment]
I edited the revises and down_revision hashes in the alembic migration. I guess it will do the trick.

**Pull request merged**
